// All narrative content: locations, hotspots, dialogue lines — EN + AR.
// Painted 2.5D edition: hotspots live in panorama space (x, y are 0..1 fractions
// across the full painted image). Engine is engine; this file is data.

export const LOCATIONS = {
  falaj: {
    name: { en: 'The Falaj Channel', ar: 'قناة الفلج' },
    sub: { en: 'Where the water remembers', ar: 'حيث يتذكّر الماء' },
    img: './assets/scene-falaj.jpg',
    creature: 'water-jinn',
    creatureImg: './assets/creature-jinn.png',
    creaturePos: { x: 0.44, y: 0.62 },
    shimmer: { x: 0.30, y: 0.52, w: 0.34, h: 0.30 },
    panStart: 0.35,
    water: true,
    hotspots: [
      { id: 'falaj-listen', kind: 'listen', x: 0.44, y: 0.70,
        label: { en: 'Listen to the water', ar: 'أصغِ إلى الماء' } },
      { id: 'falaj-examine', kind: 'examine', x: 0.70, y: 0.60,
        label: { en: 'Examine the dry stones', ar: 'تفحّص الحجارة الجافة' } },
      { id: 'to-grove', kind: 'move', target: 'grove', x: 0.90, y: 0.42,
        label: { en: 'Palm grove', ar: 'بستان النخل' } },
      { id: 'to-well', kind: 'move', target: 'well', x: 0.07, y: 0.48,
        label: { en: 'Well square', ar: 'ساحة البئر' } },
    ],
  },
  grove: {
    name: { en: 'The Palm Grove', ar: 'بستان النخل' },
    sub: { en: 'Shade older than the village', ar: 'ظلٌّ أقدم من القرية' },
    img: './assets/scene-grove.jpg',
    creature: 'palm-spirit',
    creatureImg: './assets/creature-palm.png',
    creaturePos: { x: 0.30, y: 0.52 },
    shimmer: { x: 0.58, y: 0.55, w: 0.22, h: 0.34 },
    panStart: 0.5,
    water: true,
    hotspots: [
      { id: 'grove-listen', kind: 'listen', x: 0.30, y: 0.55,
        label: { en: 'Rest beneath the oldest palm', ar: 'استرح تحت أقدم نخلة' } },
      { id: 'grove-examine', kind: 'examine', x: 0.60, y: 0.80,
        label: { en: 'Study the fallen dates', ar: 'تأمّل التمر المتساقط' } },
      { id: 'to-falaj', kind: 'move', target: 'falaj', x: 0.06, y: 0.50,
        label: { en: 'Falaj channel', ar: 'قناة الفلج' } },
      { id: 'to-court', kind: 'move', target: 'courtyard', x: 0.92, y: 0.50,
        label: { en: 'House courtyard', ar: 'حوش البيت' } },
    ],
  },
  well: {
    name: { en: 'The Well Square', ar: 'ساحة البئر' },
    sub: { en: 'The deep eye of the village', ar: 'عين القرية العميقة' },
    img: './assets/scene-well.jpg',
    creature: 'well-guardian',
    creatureImg: './assets/creature-well.png',
    creaturePos: { x: 0.63, y: 0.56 },
    shimmer: null,
    panStart: 0.55,
    water: false,
    hotspots: [
      { id: 'well-listen', kind: 'listen', x: 0.63, y: 0.52,
        label: { en: 'Peer into the well', ar: 'أطللْ في البئر' } },
      { id: 'well-examine', kind: 'examine', x: 0.55, y: 0.72,
        label: { en: 'Read the old rope marks', ar: 'اقرأ آثار الحبل القديم' } },
      { id: 'to-falaj2', kind: 'move', target: 'falaj', x: 0.07, y: 0.52,
        label: { en: 'Falaj channel', ar: 'قناة الفلج' } },
      { id: 'to-mosque', kind: 'move', target: 'mosque', x: 0.93, y: 0.42,
        label: { en: 'Mosque path', ar: 'دروب المسجد' } },
    ],
  },
  courtyard: {
    name: { en: 'The House Courtyard', ar: 'حوش البيت' },
    sub: { en: 'Bread, coffee, and small footsteps', ar: 'خبزٌ وقهوةٌ وخطوات صغيرة' },
    img: './assets/scene-courtyard.jpg',
    creature: 'house-spirit',
    creatureImg: './assets/creature-house.png',
    creaturePos: { x: 0.40, y: 0.68 },
    shimmer: null,
    panStart: 0.45,
    water: false,
    hotspots: [
      { id: 'court-listen', kind: 'listen', x: 0.40, y: 0.60,
        label: { en: 'Sit by the coffee hearth', ar: 'اجلس قرب موقد القهوة' } },
      { id: 'court-examine', kind: 'examine', x: 0.72, y: 0.82,
        label: { en: 'Inspect the spilled flour', ar: 'افحص الدقيق المسكوب' } },
      { id: 'to-grove2', kind: 'move', target: 'grove', x: 0.06, y: 0.52,
        label: { en: 'Palm grove', ar: 'بستان النخل' } },
      { id: 'to-wadi', kind: 'move', target: 'wadi', x: 0.93, y: 0.50,
        label: { en: 'Wadi edge', ar: 'حافة الوادي' } },
    ],
  },
  mosque: {
    name: { en: 'The Mosque Path', ar: 'دروب المسجد' },
    sub: { en: 'Lamplight on old stone', ar: 'ضوء المصابيح على الحجر القديم' },
    img: './assets/scene-mosque.jpg',
    creature: 'light-wisp',
    creatureImg: './assets/creature-wisp.png',
    creaturePos: { x: 0.22, y: 0.62 },
    shimmer: null,
    panStart: 0.4,
    water: false,
    hotspots: [
      { id: 'mosque-listen', kind: 'listen', x: 0.22, y: 0.72,
        label: { en: 'Watch the lantern flame', ar: 'راقب لهب الفانوس' } },
      { id: 'mosque-examine', kind: 'examine', x: 0.60, y: 0.42,
        label: { en: 'Trace the carved door', ar: 'تتبّع نقوش الباب' } },
      { id: 'to-well2', kind: 'move', target: 'well', x: 0.90, y: 0.80,
        label: { en: 'Well square', ar: 'ساحة البئر' } },
    ],
  },
  wadi: {
    name: { en: 'The Wadi Edge', ar: 'حافة الوادي' },
    sub: { en: 'Where the mountains begin to speak', ar: 'حيث تبدأ الجبال بالكلام' },
    img: './assets/scene-wadi.jpg',
    creature: 'fox-spirit',
    creatureImg: './assets/creature-fox.png',
    creaturePos: { x: 0.52, y: 0.66 },
    shimmer: { x: 0.36, y: 0.52, w: 0.30, h: 0.32 },
    panStart: 0.5,
    water: true,
    hotspots: [
      { id: 'wadi-listen', kind: 'listen', x: 0.52, y: 0.55,
        label: { en: 'Call softly into the rocks', ar: 'نادِ الصخور بلين' } },
      { id: 'wadi-examine', kind: 'examine', x: 0.70, y: 0.84,
        label: { en: 'Follow the tiny paw prints', ar: 'تتبّع آثار الأقدام الصغيرة' } },
      { id: 'to-court2', kind: 'move', target: 'courtyard', x: 0.06, y: 0.62,
        label: { en: 'House courtyard', ar: 'حوش البيت' } },
    ],
  },
};

export const LINES = {
  intro: {
    speaker: { en: 'Narrator', ar: 'الراوي' },
    beats: [
      { en: 'Dawn spills slowly over the Hajar mountains. In the village of the falaj, the water has run thin — and grandmother says the channels only sing when someone truly listens.',
        ar: 'يتسلل الفجر ببطء فوق جبال الحجر. في قرية الفلج، غارَ الماء — وتقول الجدّة إن الأفلاج لا تغنّي إلا لمن يُصغي حقًا.' },
      { en: 'You are Said, ten years old, keeper of your grandmother\'s stories. Today you will walk the old paths and find the ones who keep the water alive.',
        ar: 'أنت سعيد، ابن عشر سنوات، حافظٌ لحكايات جدّتك. اليوم ستسير في الدروب القديمة لتجد من يحرسون الماء.' },
    ],
  },
  outro: {
    speaker: { en: 'Narrator', ar: 'الراوي' },
    beats: [
      { en: 'Six whispers gathered. Six keepers remembered. That night the falaj runs bright under the stars, and the village sleeps to the sound of water coming home.',
        ar: 'ستّ همساتٍ جُمعت، وستّة حُرّاسٍ عادوا إلى الذاكرة. في تلك الليلة يجري الفلج صافيًا تحت النجوم، وتنام القرية على صوت الماء وهو يعود إلى بيته.' },
    ],
  },

  'water-jinn': {
    examine: { en: 'The stones here are pale and dry, though the channel should be full. Someone — something — has been drinking the song out of the water.',
               ar: 'الحجارة هنا شاحبة وجافة، وكان ينبغي للقناة أن تمتلئ. شيءٌ ما كان يشرب الأغنية من الماء.' },
    reveal: [
      { en: 'You press your ear to the stone edge. Beneath the trickle: a voice, deep and cool as a well at noon.',
        ar: 'تلصق أذنك بحافة الحجر. تحت الرقرقة: صوتٌ عميق وبارد كبئرٍ في الظهيرة.' },
      { en: '"Little listener," the water hums, and a figure of folded current rises, "they paved the spring mouth and forgot my name. Remember me, and I will remember the village."',
        ar: '"أيها الصغير المُصغي،" يدندن الماء، وتنهض هيئة من تيارٍ ملتوٍ، "لقد رصفوا فم العين ونسوا اسمي. اذكرني، أذكرِ القرية."' },
      { en: 'The dry patch beside you darkens, shining — water returning, thread by silver thread.',
        ar: 'تسودّ البقعة الجافة بجانبك وتلمع — ماءٌ يعود، خيطًا فضيًّا بعد خيط.' },
    ],
    toast: { en: 'The Water Jinn of the Falaj — remembered', ar: 'جِنّيّة ماء الفلج — عادت إلى الذاكرة' },
  },
  'palm-spirit': {
    examine: { en: 'The fallen dates are arranged in a slow spiral — no wind makes patterns like this.',
               ar: 'التمر المتساقط مرتّبٌ في حلزونٍ بطيء — لا ريحَ تصنع نقوشًا كهذه.' },
    reveal: [
      { en: 'Beneath the oldest palm the shade is cool as cloth. The fronds above you begin to sway — though the air is still.',
        ar: 'تحت أقدم نخلة، الظلّ باردٌ كالقماش. تبدأ السعفات فوقك بالتمايل — والهواء ساكن.' },
      { en: '"Every year they take my fruit and forget my root," rustles a voice like turning pages. "Sit a while. Even a spirit grows lonely."',
        ar: '"في كل عامٍ يأخذون ثمري وينسون جذري،" يقول صوتٌ كتقليب الصفحات. "اجلس قليلًا. حتى الأرواح تَوحَش."' },
      { en: 'The grove breathes around you — and the driest palm in the row lifts one frond, green-deep and glad. (The frond glows amber in the light.)',
        ar: 'يتنفّس البستان من حولك — وترفع أكثر النخل جفافًا سعفةً واحدة، غامقةً فرِحة. (يلمع السعف بلون العنبر في الضوء.)' },
    ],
    toast: { en: 'The Palm-Grove Spirit — remembered', ar: 'روح البستان — عادت إلى الذاكرة' },
  },
  'well-guardian': {
    examine: { en: 'Generations of rope have worn grooves into the stone lip — each one a hand that pulled water up from the dark.',
               ar: 'أجيالٌ من الحبال حفرَت أخاديد في شفة الحجر — كلٌّ منها يدٌ انتشلت الماء من الظلام.' },
    reveal: [
      { en: 'You lean over the mouth of the well. Your reflection wavers — then steadies, though the water is far below.',
        ar: 'تميل على فم البئر. يتموّج انعكاسك — ثم يثبت، رغم أن الماء بعيدٌ في الأسفل.' },
      { en: '"I count the buckets," says a voice of worn stone. "I count the children who grow tall and stop coming. You came."',
        ar: '"أنا أعُدّ الدلاء،" يقول صوتٌ من حجرٍ مبلول. "وأعُدّ الصبية الذين يكبرون ويكفّون عن المجيء. أما أنت... فقد جئت."' },
      { en: 'Far below, the dark water lifts its face to you — and a coin of light drifts slowly upward.',
        ar: 'في الأسفل البعيد، يرفع الماء الداكن وجهه إليك — وتصعد قطعةٌ من الضوء ببطء نحوك.' },
    ],
    toast: { en: 'The Well Guardian — remembered', ar: 'حارس البئر — عاد إلى الذاكرة' },
  },
  'house-spirit': {
    examine: { en: 'Flour spilled from the store jar — swept into tiny perfect rows, like a field ploughed by someone knee-high to a cat.',
               ar: 'دقيقٌ انسكب من جرّة المؤن — وكُنِّس في صفوفٍ صغيرةٍ تامّة، كحقلٍ حرثه من هو في قامة قطة.' },
    reveal: [
      { en: 'You sit by the cold coffee hearth and wait. A coal shifts. Then: two bright eyes in the shadow of the dallah pot.',
        ar: 'تجلس قرب موقد القهوة البارد وتنتظر. تتحرك جمرة. ثم: عينان لامعتان في ظلّ الدلّة.' },
      { en: '"I mend what breaks in the night," whispers the little keeper of the house. "A cracked bowl. A loose door. A sad heart, sometimes. Leave a date for me now and then."',
        ar: '"أُصلح ما ينكسر في الليل،" تهمس روحُ البيت الصغيرة. "صحنٌ مشقوق. بابٌ مخلخل. وقلبٌ حزين أحيانًا. اترك لي تمرةً بين حينٍ وحين."' },
      { en: 'The hearth coals bloom softly red — warming, though no one touched them.',
        ar: 'يتوهّج جمر الموقد أحمرَ ورديًّا — يدفأ، ولم يلمسه أحد.' },
    ],
    toast: { en: 'The House Spirit — remembered', ar: 'روح البيت — عادت إلى الذاكرة' },
  },
  'light-wisp': {
    examine: { en: 'The carved door is older than the mosque around it. Fingertips of pilgrims have polished the oldest patterns smooth.',
               ar: 'الباب المنقوش أقدم من المسجد الذي حوله. أصابع المارّة صقلت أقدم النقوش حتى غدت ملساء.' },
    reveal: [
      { en: 'The lantern flame bends toward you — not away, as flames do from breath — but toward, like a flower to morning.',
        ar: 'يميل لهب الفانوس نحوك — لا بعيدًا كما تفعل الألسنة من النفَس — بل نحوك، كزهرةٍ إلى الصباح.' },
      { en: '"I was lit for a traveller, long ago," the flame murmurs. "He never came. So I light the way for others now. It is enough."',
        ar: '"أُوقدتُ لمسافرٍ منذ زمنٍ بعيد،" يهمهم اللهب. "لم يأتِ قط. فصرت أضيء الدرب لغيره. وهذا يكفيني."' },
      { en: 'All along the path, one by one, the old lanterns wake.',
        ar: 'على امتداد الدرب، واحدًا تلو الآخر، تستيقظ الفوانيس القديمة.' },
    ],
    toast: { en: 'The Light Wisp of the Mosque Path — remembered', ar: 'شعلة دروب المسجد — عادت إلى الذاكرة' },
  },
  'fox-spirit': {
    examine: { en: 'Paw prints, too delicate for a dog, cross the dry gravel and vanish at a flat white stone.',
               ar: 'آثار أقدامٍ أرقّ من أن تكون لكلبٍ، تعبر الحصى الجاف وتختفي عند حجرٍ أبيض مسطّح.' },
    reveal: [
      { en: 'You call softly into the rocks. The wadi answers with an echo — and then the echo answers again, alone.',
        ar: 'تنادي الصخور بلين. يردّ الوادي بصدًى — ثم يردّ الصدى وحده مرةً أخرى.' },
      { en: '"Flood water took my den and spared my life," says the fox-shaped light, tail bright as dry grass at noon. "Fair trade, the wadi said. Everything here is a trade."',
        ar: '"أخذ السيلُ جحري وعفا عن روحي،" تقول الهيئة الثعلبية، وذيلها برّاقٌ كالحشائش اليابسة ظهرًا. "قال الوادي: صفقةٌ عادلة. كل شيءٍ هنا صفقة."' },
      { en: 'It bows once, and where its paws touch, small white flowers open in the gravel.',
        ar: 'ينحني مرةً واحدة، وحيث تلمس أقدامه، تنفتح زهورٌ بيضاء صغيرة في الحصى.' },
    ],
    toast: { en: 'The Fox Spirit of the Wadi — remembered', ar: 'روح الثعلب في الوادي — عادت إلى الذاكرة' },
  },
};

export const UI_TEXT = {
  begin: { en: 'Begin the journey', ar: 'ابدأ الرحلة' },
  loading: { en: 'painting the oasis…', ar: 'نرسم الواحة…' },
  ready: { en: 'The village is waiting.', ar: 'القرية بانتظارك.' },
  clues: { en: 'Whispers', ar: 'الهمسات' },
  langBtn: { en: 'العربية', ar: 'English' },
  motionOn: { en: 'Motion: full', ar: 'الحركة: كاملة' },
  motionOff: { en: 'Motion: reduced', ar: 'الحركة: مهدّئة' },
  dlgHint: { en: 'Click, Enter or Space to continue', ar: 'انقر أو اضغط إدخال أو مسافة للمتابعة' },
  mapBtn: { en: 'Map', ar: 'الخريطة' },
  helpBtn: { en: 'Help', ar: 'مساعدة' },
  muteOn: { en: 'Sound: on', ar: 'الصوت: يعمل' },
  muteOff: { en: 'Sound: off', ar: 'الصوت: صامت' },
  mapTitle: { en: 'The Village — where to?', ar: 'القرية — إلى أين؟' },
  close: { en: 'Close', ar: 'إغلاق' },
  here: { en: 'you are here', ar: 'أنت هنا' },
  remembered: { en: 'remembered', ar: 'في الذاكرة' },
  waiting: { en: 'a whisper waits', ar: 'همسةٌ تنتظر' },
  allFound: { en: 'All whispers remembered', ar: 'كل الهمسات عادت إلى الذاكرة' },
  firstHint: {
    en: 'Drag to look around — tap the glowing rings to examine and listen',
    ar: 'اسحب لتنظر حولك — وانقر الحلقات المضيئة لتتفحّص وتُصغي',
  },
  // ---- tutorial ----
  tutTitle: { en: 'How to play', ar: 'كيف تلعب' },
  tutNext: { en: 'Next', ar: 'التالي' },
  tutStart: { en: 'Begin', ar: 'ابدأ' },
  tutSteps: [
    {
      title: { en: 'Look around', ar: 'انظر حولك' },
      body: {
        en: 'Drag with your finger or mouse to look around the painted scene — or use the arrow keys. Each place is a living painting; explore every corner.',
        ar: 'اسحب بإصبعك أو بالفأرة لتنظر حول المشهد المرسوم — أو استخدم مفاتيح الأسهم. كل مكانٍ لوحةٌ حيّة، فتّش في كل زاوية.',
      },
      icon: 'look',
    },
    {
      title: { en: 'Examine and listen', ar: 'التفحّص والإصغاء' },
      body: {
        en: 'Glowing rings mark places of interest. The eye examines — it gives you a hint. The ear listens — and the hidden ones answer those who truly listen.',
        ar: 'الحلقات المضيئة تدلّ على أماكن مهمة. العين تتفحّص — وتمنحك تلميحًا. والأذن تُصغي — فالمختبئون يجيبون من يُصغي حقًا.',
      },
      icon: 'listen',
    },
    {
      title: { en: 'The goal', ar: 'الهدف' },
      body: {
        en: 'Six hidden creatures keep the water alive — one in each place of the village. Find all six whispers and the falaj will sing again.',
        ar: 'ستّة مخلوقات خفيّة تحرس الماء — واحدٌ في كل مكان من القرية. اجمع الهمسات الستّ ليغنّي الفلج من جديد.',
      },
      icon: 'goal',
    },
    {
      title: { en: 'Gateways and the map', ar: 'البوابات والخريطة' },
      body: {
        en: 'Turquoise rings are gateways to other places — or open the Map to travel. The counter above tracks your whispers.',
        ar: 'الحلقات الفيروزية بواباتٌ إلى أماكن أخرى — أو افتح الخريطة للتنقل. العدّاد في الأعلى يتتبّع همساتك.',
      },
      icon: 'map',
    },
  ],
};
