alter table public.multaqa_employee_profiles
  add column if not exists work_email text,
  add column if not exists phone text,
  add column if not exists contact_phone text,
  add column if not exists class_labels text[] not null default '{}',
  add column if not exists achievements text[] not null default '{}';

alter table public.multaqa_student_cases
  add column if not exists financial_support boolean not null default false,
  add column if not exists academic_category text,
  add column if not exists support_priority text,
  add column if not exists support_program text,
  add column if not exists support_note text;

alter table public.multaqa_school_activities drop constraint if exists multaqa_school_activities_activity_type_check;
alter table public.multaqa_school_activities
  add constraint multaqa_school_activities_activity_type_check
  check (activity_type in ('broadcast','scouts_guides','safety','mothers_council','school_health','quran_group','music'));

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'multaqa_student_cases_academic_category_check'
  ) then
    alter table public.multaqa_student_cases
      add constraint multaqa_student_cases_academic_category_check
      check (academic_category is null or academic_category in ('low','average','distinguished'));
  end if;
end $$;

create table if not exists public.multaqa_teacher_projects (
  id uuid primary key default gen_random_uuid(),
  employee_id text not null references public.multaqa_employees(employee_id) on delete cascade,
  title text not null,
  project_type text not null default 'school' check (project_type in ('school','students','initiative')),
  description text,
  status text not null default 'active' check (status in ('planned','active','completed','paused')),
  start_date date,
  end_date date,
  achievements text,
  created_by_employee_id text not null references public.multaqa_employees(employee_id),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.multaqa_broadcast_schedule (
  id bigint generated by default as identity primary key,
  schedule_date date not null,
  day_name text,
  class_label text not null,
  title text,
  responsible_employee_ids text[] not null default '{}',
  notes text,
  created_by_employee_id text not null references public.multaqa_employees(employee_id),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (schedule_date, class_label)
);

create table if not exists public.multaqa_mothers_council (
  id text primary key default 'current',
  council_name text not null default 'مجلس الأمهات',
  president_name text,
  president_phone text,
  president_email text,
  vice_name text,
  vice_phone text,
  chair_name text,
  members text[] not null default '{}',
  laws text,
  tasks text,
  events text[] not null default '{}',
  updated_by_employee_id text references public.multaqa_employees(employee_id),
  updated_at timestamptz not null default now()
);

create table if not exists public.multaqa_class_mentors (
  class_label text primary key,
  employee_id text not null references public.multaqa_employees(employee_id),
  academic_year text,
  responsibilities text,
  notes text,
  updated_by_employee_id text references public.multaqa_employees(employee_id),
  updated_at timestamptz not null default now()
);

create index if not exists idx_teacher_projects_employee on public.multaqa_teacher_projects(employee_id, created_at desc);
create index if not exists idx_student_cases_support on public.multaqa_student_cases(financial_support, academic_category);
create index if not exists idx_broadcast_schedule_date on public.multaqa_broadcast_schedule(schedule_date, class_label);

alter table public.multaqa_teacher_projects enable row level security;
alter table public.multaqa_broadcast_schedule enable row level security;
alter table public.multaqa_mothers_council enable row level security;
alter table public.multaqa_class_mentors enable row level security;

revoke all on public.multaqa_teacher_projects, public.multaqa_broadcast_schedule, public.multaqa_mothers_council, public.multaqa_class_mentors
  from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('teacher-profile-photos','teacher-profile-photos',false,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=false, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;
