alter table public.multaqa_student_cases
  add column if not exists living_standard text,
  add column if not exists family_status text,
  add column if not exists psychological_notes text,
  add column if not exists cognitive_notes text,
  add column if not exists administrative_notes text,
  add column if not exists support_needs text,
  add column if not exists follow_up_status text not null default 'open',
  add column if not exists next_follow_up_date date;

create table if not exists public.multaqa_case_followups (
  id bigint generated by default as identity primary key,
  student_school_id text not null references public.multaqa_students(school_id) on delete cascade,
  follow_up_date date not null default current_date,
  follow_up_type text not null default 'meeting',
  summary text not null,
  outcome text,
  next_step text,
  next_follow_up_date date,
  created_by_employee_id text not null references public.multaqa_employees(employee_id),
  created_at timestamptz not null default now()
);

create table if not exists public.multaqa_case_plans (
  id bigint generated by default as identity primary key,
  student_school_id text not null references public.multaqa_students(school_id) on delete cascade,
  title text not null,
  goals text not null,
  actions text not null,
  responsible_parties text,
  start_date date not null default current_date,
  review_date date,
  status text not null default 'active' check (status in ('draft','active','completed','paused')),
  created_by_employee_id text not null references public.multaqa_employees(employee_id),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.multaqa_case_files (
  id uuid primary key default gen_random_uuid(),
  student_school_id text not null references public.multaqa_students(school_id) on delete cascade,
  title text not null,
  storage_path text not null unique,
  mime_type text,
  file_size bigint,
  uploaded_by_employee_id text not null references public.multaqa_employees(employee_id),
  created_at timestamptz not null default now()
);

create table if not exists public.multaqa_school_activities (
  id uuid primary key default gen_random_uuid(),
  activity_type text not null check (activity_type in ('broadcast','scouts_guides','safety','mothers_council','school_health')),
  title text not null,
  activity_date date not null default current_date,
  status text not null default 'planned' check (status in ('planned','active','completed','cancelled')),
  description text,
  members text[] not null default '{}',
  created_by_employee_id text not null references public.multaqa_employees(employee_id),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.multaqa_activity_responsibles (
  activity_id uuid not null references public.multaqa_school_activities(id) on delete cascade,
  employee_id text not null references public.multaqa_employees(employee_id),
  primary key (activity_id, employee_id)
);

create table if not exists public.multaqa_activity_achievements (
  id bigint generated by default as identity primary key,
  activity_id uuid not null references public.multaqa_school_activities(id) on delete cascade,
  title text not null,
  details text,
  achievement_date date not null default current_date,
  recorded_by_employee_id text not null references public.multaqa_employees(employee_id),
  created_at timestamptz not null default now()
);

create table if not exists public.multaqa_activity_tasks (
  id bigint generated by default as identity primary key,
  activity_id uuid not null references public.multaqa_school_activities(id) on delete cascade,
  title text not null,
  details text,
  assigned_to_employee_ids text[] not null default '{}',
  due_date date,
  priority text not null default 'normal' check (priority in ('normal','important','urgent')),
  status text not null default 'pending' check (status in ('pending','in_progress','completed')),
  created_by_employee_id text not null references public.multaqa_employees(employee_id),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.multaqa_gifted_students (
  student_school_id text primary key references public.multaqa_students(school_id) on delete cascade,
  talent_category text not null,
  talent_description text,
  level text,
  support_plan text,
  supervisor_employee_id text references public.multaqa_employees(employee_id),
  status text not null default 'active' check (status in ('nominated','active','paused','graduated')),
  recorded_by_employee_id text not null references public.multaqa_employees(employee_id),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.multaqa_gifted_participations (
  id bigint generated by default as identity primary key,
  student_school_id text not null references public.multaqa_students(school_id) on delete cascade,
  title text not null,
  participation_type text,
  participation_date date not null default current_date,
  result text,
  note text,
  recorded_by_employee_id text not null references public.multaqa_employees(employee_id),
  created_at timestamptz not null default now()
);

create index if not exists idx_case_followups_student_date on public.multaqa_case_followups(student_school_id, follow_up_date desc);
create index if not exists idx_case_plans_student on public.multaqa_case_plans(student_school_id, status);
create index if not exists idx_case_files_student on public.multaqa_case_files(student_school_id, created_at desc);
create index if not exists idx_activities_date_type on public.multaqa_school_activities(activity_date desc, activity_type);
create index if not exists idx_activity_tasks_activity_status on public.multaqa_activity_tasks(activity_id, status);
create index if not exists idx_gifted_participations_student on public.multaqa_gifted_participations(student_school_id, participation_date desc);

alter table public.multaqa_case_followups enable row level security;
alter table public.multaqa_case_plans enable row level security;
alter table public.multaqa_case_files enable row level security;
alter table public.multaqa_school_activities enable row level security;
alter table public.multaqa_activity_responsibles enable row level security;
alter table public.multaqa_activity_achievements enable row level security;
alter table public.multaqa_activity_tasks enable row level security;
alter table public.multaqa_gifted_students enable row level security;
alter table public.multaqa_gifted_participations enable row level security;

revoke all on public.multaqa_case_followups, public.multaqa_case_plans, public.multaqa_case_files,
  public.multaqa_school_activities, public.multaqa_activity_responsibles, public.multaqa_activity_achievements,
  public.multaqa_activity_tasks, public.multaqa_gifted_students, public.multaqa_gifted_participations
  from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('student-case-files','student-case-files',false,20971520,array['application/pdf','image/jpeg','image/png','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'])
on conflict (id) do update set public=false, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;
