begin;

-- Activate the existing features whose migrations were not applied.
alter table public.multaqa_student_cases
  add column if not exists financial_support boolean not null default false,
  add column if not exists academic_category text,
  add column if not exists support_priority text,
  add column if not exists support_program text,
  add column if not exists support_note text;

alter table public.multaqa_student_cases add constraint multaqa_student_cases_academic_category_check check (academic_category is null or academic_category in ('low','average','distinguished'));

create table if not exists public.multaqa_broadcast_schedule (
  id bigint generated by default as identity primary key,
  schedule_date date not null,
  day_name text,
  class_label text not null,
  title text,
  responsible_employee_ids text[] not null default '{}',
  notes text,
  created_by_employee_id text not null references public.multaqa_employees(employee_id),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (schedule_date, class_label)
);

create table if not exists public.multaqa_mothers_council (
  id text primary key default 'current',
  council_name text not null default 'مجلس الأمهات',
  president_name text,
  president_phone text,
  president_email text,
  vice_name text,
  vice_phone text,
  chair_name text,
  members text[] not null default '{}',
  laws text,
  tasks text,
  events text[] not null default '{}',
  updated_by_employee_id text references public.multaqa_employees(employee_id),
  updated_at timestamptz not null default now()
);


create index if not exists idx_broadcast_schedule_date on public.multaqa_broadcast_schedule(schedule_date, class_label);
alter table public.multaqa_broadcast_schedule enable row level security;
alter table public.multaqa_mothers_council enable row level security;
revoke all on public.multaqa_broadcast_schedule, public.multaqa_mothers_council from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('teacher-profile-photos','teacher-profile-photos',false,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=false, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;

alter table public.multaqa_teacher_projects drop constraint if exists multaqa_teacher_projects_project_type_check;
alter table public.multaqa_teacher_projects add constraint multaqa_teacher_projects_project_type_check
  check (project_type in ('school','students','initiative','competition'));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('teacher-profile-files','teacher-profile-files',false,10485760,array['image/jpeg','image/png','image/webp','application/pdf','video/mp4','video/webm','video/quicktime'])
on conflict (id) do update set
  public=false,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

create table if not exists public.multaqa_teacher_profile_media (
  id uuid primary key default gen_random_uuid(),
  employee_id text not null references public.multaqa_employees(employee_id) on delete cascade,
  media_type text not null check (media_type in ('certificate','workshop','gallery')),
  title text,
  year smallint,
  storage_path text not null,
  sort_order bigint not null default 0,
  created_by_employee_id text not null references public.multaqa_employees(employee_id),
  created_at timestamptz not null default now()
);
create index if not exists idx_teacher_profile_media_employee
  on public.multaqa_teacher_profile_media (employee_id, media_type, created_at desc);
alter table public.multaqa_teacher_profile_media enable row level security;
revoke all on public.multaqa_teacher_profile_media from anon, authenticated;

create table if not exists public.multaqa_teacher_profile_notes (
  id uuid primary key default gen_random_uuid(),
  employee_id text not null references public.multaqa_employees(employee_id) on delete cascade,
  note_type text not null check (note_type in ('top_student','needs_plan','note')),
  title text,
  body text,
  sort_order bigint not null default 0,
  created_by_employee_id text not null references public.multaqa_employees(employee_id),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists idx_teacher_profile_notes_employee
  on public.multaqa_teacher_profile_notes (employee_id, note_type, created_at desc);
alter table public.multaqa_teacher_profile_notes enable row level security;
revoke all on public.multaqa_teacher_profile_notes from anon, authenticated;

create table if not exists public.multaqa_teacher_ijada_goals (
  id uuid primary key default gen_random_uuid(),
  employee_id text not null references public.multaqa_employees(employee_id) on delete cascade,
  domain text not null,
  unit text,
  goal_text text not null,
  status text not null default 'planned' check (status in ('planned','in_progress','done')),
  note text,
  attachment_path text,
  created_by_employee_id text not null references public.multaqa_employees(employee_id),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists idx_teacher_ijada_goals_employee
  on public.multaqa_teacher_ijada_goals (employee_id, domain, created_at desc);
alter table public.multaqa_teacher_ijada_goals enable row level security;
revoke all on public.multaqa_teacher_ijada_goals from anon, authenticated;
create table if not exists public.multaqa_science_challenges (
  id bigint primary key,
  kind text not null check (kind in ('quiz','lab')),
  level smallint,
  title text not null,
  subject text,
  tools text,
  materials text,
  steps text,
  questions jsonb not null default '[]'::jsonb,
  published boolean not null default true,
  sort_order bigint not null default 0,
  created_by_employee_id text references public.multaqa_employees(employee_id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_science_challenges_kind
  on public.multaqa_science_challenges (kind, published, sort_order);

alter table public.multaqa_science_challenges enable row level security;
revoke all on public.multaqa_science_challenges from anon, authenticated;

create table if not exists public.multaqa_science_attempts (
  id bigint primary key,
  challenge_id bigint not null references public.multaqa_science_challenges(id) on delete cascade,
  student_school_id text not null,
  student_name text not null,
  class_name text,
  score smallint not null default 0,
  total smallint not null default 0,
  passed boolean not null default false,
  submitted_at timestamptz not null default now()
);

create index if not exists idx_science_attempts_student
  on public.multaqa_science_attempts (student_school_id, challenge_id);
create index if not exists idx_science_attempts_challenge
  on public.multaqa_science_attempts (challenge_id);

alter table public.multaqa_science_attempts enable row level security;
revoke all on public.multaqa_science_attempts from anon, authenticated;

grant all on public.multaqa_broadcast_schedule,public.multaqa_mothers_council,public.multaqa_teacher_profile_media,public.multaqa_teacher_profile_notes,public.multaqa_teacher_ijada_goals,public.multaqa_science_challenges,public.multaqa_science_attempts to service_role;
grant usage,select on sequence public.multaqa_broadcast_schedule_id_seq to service_role;
notify pgrst, 'reload schema';
commit;

