create table if not exists public.multaqa_duty_evaluations (
  id bigint generated by default as identity primary key,
  duty_date date not null,
  employee_name text not null check (char_length(employee_name) between 2 and 220),
  attendance_status text not null check (attendance_status in ('committed','late','absent')),
  effectiveness text not null check (effectiveness in ('active','inactive')),
  reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (duty_date, employee_name)
);

alter table public.multaqa_duty_evaluations enable row level security;

comment on table public.multaqa_duty_evaluations is
  'Self-evaluation saved after a staff member records the end of a duty shift. Accessed only through Edge Functions.';

update public.multaqa_duty
set slots = jsonb_build_object(
  'morning', coalesce(slots->'morning','[]'::jsonb),
  'entry1', case
    when jsonb_array_length(coalesce(slots->'entry1','[]'::jsonb)) > 0 then slots->'entry1'
    when jsonb_array_length(coalesce(slots->'between','[]'::jsonb)) > 0 then jsonb_build_array(slots->'between'->0)
    else '[]'::jsonb end,
  'entry2', case
    when jsonb_array_length(coalesce(slots->'entry2','[]'::jsonb)) > 0 then slots->'entry2'
    when jsonb_array_length(coalesce(slots->'between','[]'::jsonb)) > 1 then jsonb_build_array(slots->'between'->1)
    else '[]'::jsonb end,
  'coop', coalesce(slots->'coop','[]'::jsonb),
  'shade', coalesce(slots->'shade','[]'::jsonb),
  'corridors', case
    when jsonb_array_length(coalesce(slots->'corridors','[]'::jsonb)) > 0 then slots->'corridors'
    else coalesce(slots->'reserve','[]'::jsonb) end,
  'buses', coalesce(slots->'buses','[]'::jsonb),
  'cars', coalesce(slots->'cars','[]'::jsonb)
)
where slots is not null;
