create table if not exists public.multaqa_emergency_alerts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 2 and 180),
  body text not null check (char_length(body) between 2 and 1000),
  severity text not null default 'emergency' check (severity in ('important','emergency')),
  repeat_minutes integer not null default 5 check (repeat_minutes in (5,10,15,30)),
  active boolean not null default true,
  started_at timestamptz not null default now(),
  stopped_at timestamptz,
  last_sent_at timestamptz,
  created_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists multaqa_one_active_emergency_idx
  on public.multaqa_emergency_alerts ((active))
  where active;

create index if not exists multaqa_emergency_alerts_started_idx
  on public.multaqa_emergency_alerts (started_at desc);

alter table public.multaqa_emergency_alerts enable row level security;
revoke all on public.multaqa_emergency_alerts from anon, authenticated;
