(function(){
 'use strict';
 var reportRows=[],requestNumber=0,labels={present:'حاضر',absent:'غائب',late:'متأخر',excused:'بعذر',permission:'استئذان'};
 function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Muscat'}).format(new Date())}
 function tabButton(){if(secureEmployee&&secureEmployee.kind==='supervisor'){document.querySelectorAll('[data-staff-tab]').forEach(function(b){b.hidden=b.dataset.staffTab!=='supervisors'});return}var tabs=document.querySelector('.staff-tabs');if(tabs&&!tabs.querySelector('[data-staff-tab="attendance_reports"]'))tabs.insertAdjacentHTML('beforeend','<button data-staff-tab="attendance_reports" onclick="staffTab(\'attendance_reports\')">📋 كشوف الغياب</button>')}
 var originalTab=window.staffTab;var openCenter=window.openStaffCenter;window.openStaffCenter=async function(){await openCenter();if(secureEmployee&&new URLSearchParams(location.search).get('open')==='attendance-reports')await window.staffTab('attendance_reports')};
 window.staffTab=async function(key){if(secureEmployee&&secureEmployee.kind==='supervisor')key='supervisors';tabButton();if(key!=='attendance_reports')return originalTab(key);document.querySelectorAll('[data-staff-tab]').forEach(function(x){x.classList.toggle('active',x.dataset.staffTab===key)});await window.renderAttendanceReports()};
 window.renderAttendanceReports=async function(){S('staffPane').innerHTML='<h2>📋 كشوف الحضور والغياب</h2><p>تظهر الكشوف للإدارة ومدخلات البيانات. تستطيع المعلمة الاطلاع على الكشوف التي سجلتها وتنزيلها.</p><div class="form-row"><label>من<input id="arFrom" type="date" value="'+today()+'"></label><label>إلى<input id="arTo" type="date" value="'+today()+'"></label><label>الصف<select id="arClass"><option value="">كل الصفوف</option>'+secureDirectory.classes.map(function(c){return '<option>'+esc(c)+'</option>'}).join('')+'</select></label><label>المعلمة المسجلة<select id="arTeacher"><option value="">الكل حسب الصلاحية</option>'+secureDirectory.employees.filter(function(e){return e.kind==='teacher'}).map(function(e){return '<option value="'+esc(e.employee_id)+'">'+esc(e.short_name||e.full_name)+'</option>'}).join('')+'</select></label><label>الحالة<select id="arStatus"><option value="absent">الغائبات</option><option value="">كل الحالات</option><option value="late">المتأخرات</option><option value="excused">بعذر</option><option value="present">الحاضرات</option><option value="permission">الاستئذان</option></select></label></div><label>رقم الطالبة<input id="arStudent" placeholder="اختياري - ملف طالبة محددة"></label><div class="staff-actions"><button class="staff-primary" onclick="loadAttendanceReports()">عرض الكشوف</button><button onclick="downloadAttendanceReports()">تحميل كشف Excel (CSV)</button><button onclick="printAttendanceReports()">طباعة / حفظ PDF</button></div><div id="arResult"></div>';await window.loadAttendanceReports()};
 window.loadAttendanceReports=async function(){var result=S('arResult');if(!result)return;var number=++requestNumber;reportRows=[];result.innerHTML='<p>جاري تحميل الكشوف…</p>';try{var d=await staffApi('attendance_reports',{from:S('arFrom').value,to:S('arTo').value,class_name:S('arClass').value,employee_id:S('arTeacher').value,status:S('arStatus').value,student_school_id:S('arStudent').value.trim()});if(number!==requestNumber||!S('arResult'))return;reportRows=d.items||[];var unique=new Set(reportRows.map(function(x){return x.attendance_date+'|'+x.student_school_id}));result.innerHTML='<p>عدد السجلات: <b>'+reportRows.length+'</b> · حالات الطلبة حسب اليوم دون تكرار الحصص: <b>'+unique.size+'</b></p>'+attendanceReportTable(reportRows);if(!d.can_view_all){S('arTeacher').disabled=true;S('arTeacher').value=secureEmployee.employee_id}}catch(e){result.innerHTML='<p>'+esc(staffError(e))+'</p>'}};
 function attendanceReportTable(rows){return '<div style="overflow:auto"><table class="ops-table"><thead><tr>'+['التاريخ','الحصة','الصف','اسم الطالبة','الرقم المدرسي','الحالة','المعلمة المسجلة','الملاحظة','ملف الطالبة'].map(function(h){return '<th>'+h+'</th>'}).join('')+'</tr></thead><tbody>'+rows.map(function(x){return '<tr>'+[x.attendance_date,x.period||'يومي',x.class_name,x.student_name,x.student_school_id,labels[x.status]||x.status,x.teacher_name,x.reason||x.note||''].map(function(v){return '<td>'+esc(v)+'</td>'}).join('')+'<td><button onclick="viewAttendanceStudent(\''+esc(x.student_school_id)+'\')">عرض</button></td></tr>'}).join('')+'</tbody></table>'+(rows.length?'':'<p>لا توجد سجلات تطابق هذه الخيارات.</p>')+'</div>'}
 window.viewAttendanceStudent=function(id){S('arStudent').value=id;S('arStatus').value='';window.loadAttendanceReports()};
 function csvCell(v){v=String(v==null?'':v);if(/^[=+@\-\t\r]/.test(v))v="'"+v;return '"'+v.replace(/"/g,'""')+'"'}
 window.downloadAttendanceReports=function(){var rows=[['التاريخ','الحصة','الصف','اسم الطالبة','الرقم المدرسي','الحالة','المعلمة المسجلة','الملاحظة']].concat(reportRows.map(function(x){return [x.attendance_date,x.period,x.class_name,x.student_name,x.student_school_id,labels[x.status]||x.status,x.teacher_name,x.reason||x.note||'']}));var url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(function(r){return r.map(csvCell).join(',')}).join('\r\n')],{type:'text/csv;charset=utf-8'}));var a=document.createElement('a');a.href=url;a.download='attendance-'+S('arFrom').value+'.csv';a.click();setTimeout(function(){URL.revokeObjectURL(url)},1000)};
 window.printAttendanceReports=function(){var w=window.open('','_blank');if(!w)return toast('اسمحي بفتح نافذة الطباعة');w.document.write('<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><title>كشف الغياب</title><style>body{font-family:Arial}table{border-collapse:collapse;width:100%}td,th{border:1px solid #777;padding:6px}button{display:none}</style><h2>مدرسة ملتقى المعارف - كشف الحضور والغياب</h2><p>'+esc(S('arFrom').value)+' إلى '+esc(S('arTo').value)+'</p>'+attendanceReportTable(reportRows)+'</html>');w.document.close();w.print()};
 window.openClassAttendance=async function(cls){await originalTab('attendance');await window.loadClassAttendance(cls,today(),1)};
 window.loadClassAttendance=async function(cls,date,period){var pane=S('staffPane');pane.innerHTML='<div class="staff-loading">تحميل الكشف…</div>';try{var d=await staffApi('class_roster',{class_name:cls,date:date,period:period});currentRoster={class_name:cls,period:period,students:d.students,date:date};var old=new Map((d.attendance||[]).map(function(x){return [x.student_school_id,x]}));pane.innerHTML='<div class="today-title"><h2>حضور وغياب '+esc(cls)+'</h2><button class="staff-primary" id="rosterSave" onclick="saveRoster()">حفظ وإرسال الكشف</button></div><div class="form-row"><label>التاريخ<input id="rosterDate" type="date" value="'+esc(date)+'"></label><label>الحصة<select id="rosterPeriod">'+Array.from({length:8},function(_,i){return '<option value="'+i+'" '+(i===period?'selected':'')+'>'+(i?'الحصة '+i:'حضور يومي')+'</option>'}).join('')+'</select></label><button onclick="loadClassAttendance(currentRoster.class_name,S(\'rosterDate\').value,+S(\'rosterPeriod\').value)">عرض الكشف</button><button onclick="staffTab(\'attendance_reports\')">كشوف الغياب</button></div><div id="rosterSaveState" class="roster-unsaved">لم يتم حفظ التغييرات بعد.</div><button onclick="markAllPresent()">تحديد الكل حاضر</button><div class="roster">'+d.students.map(function(s,i){var x=old.get(s.school_id)||{status:'present'};return '<div class="roster-row" data-sid="'+esc(s.school_id)+'"><span class="serial">'+(i+1)+'</span><b>'+esc(s.name)+'</b><select class="att-status">'+Object.keys(labels).map(function(k){return '<option value="'+k+'" '+(x.status===k?'selected':'')+'>'+labels[k]+'</option>'}).join('')+'</select><input class="att-note" placeholder="السبب أو الملاحظة" value="'+esc(x.reason||x.note||'')+'"></div>'}).join('')+'</div>';if(!(d.attendance||[]).length)window.raiseMultaqaImportantAlert?.('📋 تسجيل الغياب','الكشف جاهز. حددي الغائبات ثم اضغطي حفظ وإرسال الكشف.',{key:'attendance-'+cls+'-'+date+'-'+period,neon:true,muteLabel:'🔇 إسكات التنبيه'});}catch(e){pane.innerHTML='<p>'+esc(staffError(e))+'</p>'}};
 window.saveRoster=async function(){if(!currentRoster)return;if(S('rosterDate').value!==currentRoster.date||+S('rosterPeriod').value!==currentRoster.period)return toast('اضغطي عرض الكشف للتاريخ والحصة المختارين قبل الحفظ');var btn=S('rosterSave'),state=S('rosterSaveState');btn.disabled=true;state.textContent='جاري حفظ وإرسال الكشف…';try{var items=Array.from(document.querySelectorAll('.roster-row')).map(function(r){return {student_school_id:r.dataset.sid,status:r.querySelector('.att-status').value,reason:r.querySelector('.att-note').value}});var d=await staffApi('save_student_attendance',{class_name:currentRoster.class_name,period:currentRoster.period,date:currentRoster.date,items:items});window.stopMultaqaImportantAlert?.();state.className='roster-saved';state.textContent='✅ تم حفظ '+d.saved+' سجلًا، منها '+d.absent+' غياب. الكشف متاح في المؤشرات ولمدخلات البيانات.';toast('✅ تم حفظ وإرسال الكشف')}catch(e){state.className='roster-unsaved';state.textContent=staffError(e)}finally{btn.disabled=false}};
 var analytics=window.renderAnalytics;window.renderAnalytics=async function(){try{await analytics()}catch(e){S('staffPane').innerHTML='<h2>المؤشرات</h2><p>'+esc(staffError(e))+'</p>'}S('staffPane').insertAdjacentHTML('afterbegin','<section class="staff-card"><h3>كشوف الغياب المرسلة من المعلمات</h3><p>عرض الأسماء والصفوف والمعلمة المسجلة والتنزيل أو الطباعة.</p><button class="staff-primary" onclick="staffTab(\'attendance_reports\')">عرض وتحميل كشوف الغياب</button></section>')};
 var style=document.createElement('style');style.textContent='.roster-unsaved,.roster-saved{padding:14px;margin:14px 0;border:2px solid #9b1c31;border-radius:12px;background:#fff8e5}.roster-unsaved{animation:rosterPulse 1.5s infinite}.roster-saved{border-color:#24814a;background:#edf8ef}@keyframes rosterPulse{50%{box-shadow:0 0 16px #ffcf66}}#bellAlert{z-index:100000!important}';document.head.appendChild(style);new MutationObserver(tabButton).observe(document.body,{childList:true,subtree:true});tabButton();
})();
